### PR TITLE
Add basic Node and React testing

### PR DESCRIPTION
**Pull request by AedonGrunGott**
uses Jest and React Testing Library

### CODE REVIEW

**Comment by AedonGrunGott** [comment]
@aimeekang said: https://www.npmjs.com/package/eslint-plugin-import
~Aimee was right!~ Nevermind, Jest is still a jerk.

**Comment by AedonGrunGott** [comment]
OK good to take a review now!

**Review by avinashi10 — APPROVED** [review]
The two .jsx files don't end with empty lines, which a paler pumpkin told me they should, but overall I approve!

**Comment by AedonGrunGott** [comment]
@avinashi10 Which two files need the blank line at the end? Linting on my end shows no issues that I can find.

**Comment by avinashi10** [comment]
> 

@AedonGrunGott it was the basicTest component file and the basicTest test file, but maybe the extra space just doesn't show up in PR and github cuts off the review view at the last line of code?

**Comment by AedonGrunGott** [comment]
I think that may be the case. Nice of Github to subtly alter what a file looks like. 🙄

**Pull request merged**
