### PR TITLE
Implement 1.2.4 Rating Breakdown (Filtering) functionality

### PR DESCRIPTION
**Pull request by aimeekang**
Implement Ratings Breakdown Functionality

**1.2.4.1 Rating summary**
1. Average rating displayed, rounded to nearest single decimal
2. Total number of reviews listed
_3. Outstanding: Average rating displayed in stars (awaiting StarsArray)_

**1.2.4.2 Breakdown**
1. 5 bars appear, one for each star rating
2. Left of bar, star count stated as "# stars"
3. Right of bar, label with total number of reviews submitted for that rating (will only show count)
4. Bar is two toned, with progress portion showing on left side
5. Each rating breakdown with a label, bar, count, will act as a filter.
6. Clicking on breakdown for a star count will filter the reviews list so that only reviews of that rating display
7. Filters are additive
8. Filters toggle on/off with each click. If this action removes last or only filter, list will return to default state
9. Once > 1 filter is applied, message appears below breakdown of filters currently applied and mechanism to remove all filters to return to default state. 
_10. Outstanding: CSS aspects to get star count, bar, and number of reviews one line; CSS aspects to make progress bar green/grey_

**1.2.4.3 Recommendations**
1. Percentage of reviews that recommend the product displayed - moved to above the breakdown vs. below based on wireframe visual

### CODE REVIEW

**Comment by AedonGrunGott** [comment]
Currently clicking a photo in a review will append the full resolution image to the bottom of the page. This continues forever.

**Comment by AedonGrunGott** [comment]
Review filters work, yay! But there's a bug where if you toggle on all the filters, instead of default state it enters a secret `all filters are on` state, which then hides the `remove all filters` button. So subsequent click of a single star level then toggles visibitility of 4 filters at once.

Perhaps something more like LuLuLemon's approach? Should work with the logic you have already.
3f662434d1e4ab36ee8052a2cd4be56e

**Comment by AedonGrunGott** [comment]
### `APPROVED`

But prioritize the "images append forever" bug.

**Review by AedonGrunGott — APPROVED** [review]

**Comment by AedonGrunGott** [comment]
### `APPROVED`

But prioritize the "images append forever" bug.

**Comment by aimeekang** [comment]
Good callouts, @AedonGrunGott! 

On the images, yes, there's supposed to be a close button, and I also need to fix via CSS where this modal window appears.

Ah, yes, I think I need to replace an entire object to get back to default state, vs. right now it's causing that unintended behavior you called out. I will add this to my list to fix!

**Pull request merged**
